---
spec:
  replicas: 1
  template:
    spec:
      containers:
      - env:
         -  name: AWS_REGION
            value: ${aws.region}
         -  name: RDS_HOST
            value: ${rds.host}
         -  name: RDS_PORT
            value: ${rds.port}
         -  name: RDS_DATABASE
            value: ${rds.db}
        imagePullPolicy: Always
      serviceAccountName: rosa-demo-sa
