= Deploy Service
include::_attributes.adoc[]
= AWS RDS

A simple REST API that uses https://aws.amazon.com/rds/[AWS RDS] as its data store.

At end of this chapter you will be able to:

* Setup AWS RDS PostgreSQL
* Use the `ROSADemosRole` with OpenShift SA
* Deploy the `FruitsApp` Java Application
* Check and verify only authorized OpenShift SA is able peform CRUD on PostgreSQL table *fruitsapp*

[#aws-rds-pre-req]
== Pre-Requisites

Ensure that you have completed the following before running the exercises of this chapter:

* xref:setup.adoc#setup-rosa[ROSA Cluster Setup]
* All steps in xref:aws-iam.adoc#prep-aws-iam[AWS IAM] is completed 

[#setup-rds]
== Setup RDS PostgreSQL

[#rds-nav-folder]
Navigate to the tutorial folder:

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
cd $TUTORIAL_HOME/rds
----

Ensure you are on the right OpenShift project `rosa-demos`:

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc project -q
----

[#connect-rds]
== Connect to RDS PostgreSQL

*TODO*

[#setup-build-service-ui]
include::ROOT:partial$apps.adoc[tags="ui"]

[#rds-build-service]
== Build Service

The Fruits API Java Application can be deployed as https://quarkus.io[Quarkus] or  https://springboot.io[Spring Boot]. 

The following section details on how to deploy them.

[#rds-build-prereq]
=== Pre-Requisite

Lets ensure if all the required environment variables are setup correctly

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
export AWS_REGION='<your aws_region value>'#<.>
----
<.> The AWS region to use

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
export ROSA_DEMO_ROLE_ARN=$(aws iam get-role --role-name --output json ROSADemosRole | jq -r '.Role.Arn')#<.>
----
<.> The AWS Role ARN for the `ROSADemosRole` IAM role

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
export RDS_HOST=$(aws rds describe-db-instances --output json | jq -r '.DBInstances[0].Endpoint.Address')#<.>
----
<.> The RDS PostgreSQL endpoint address

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
export RDS_PORT=$(aws rds describe-db-instances --output json | jq -r '.DBInstances[0].Endpoint.Port')#<.>
----
<.> The RDS PostgreSQL Port 

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
export RDS_DATABASE="fruitsdb"#<.>
----
<.> The RDS Database which is *fruitsdb*

[#rds-build-quarkus-service]
=== Quarkus

include::ROOT:partial$commands.adoc[tags="quarkus"]

[#rds-build-sb-service]
=== Spring Boot

include::ROOT:partial$commands.adoc[tags="springboot"]

[#aws-rds-check-apps]
=== Check Application Deployments

Once the maven build completes successfully you can check the status of the application deployment:

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc get deploy -n rosa-demos
----

Based on which variant of Application you deployed *Quarkus* or *SpringBoot* you should see an output as shown below. Assuming the *Quarkus* variant deployed:

[.console-output]
[source,bash,subs="quotes"]
----
NAME                      READY   UP-TO-DATE   AVAILABLE   AGE
db-adminer                1/1     1            1           19h
pgsql-client              1/1     1            1           14h
#rosa-fruits-app-quarkus   1/1     1            1           4h48m#
----

[NOTE]
====
You can also verify the same via ROSA OpenShift Web Console by navigating to `rosa-demos` project
====

[#aws-rds-verify-apps]
== Check Application Deployments

include::ROOT:partial$verify_app.adoc[]

[#aws-rds-verify-access]
== Verify Access

To make sure the IAM works, try deploying the application a different namespace, for e.g. `demos`

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc new-project demos
----

Now do the <<rds-build-quarkus-service,Quarkus>> or <<rds-build-sb-service,SpringBoot>> deployment on the `demos` namespace.

Check the logs of the `rosa-fruits-app-[quarkus|springboot]` using `stern`

Assuming I deployed the `rosa-fruits-app-quarkus`,

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
stern rosa-fruits-app
----

You should notice errors on the log, something similar to,

[.console-output]
[source,bash,subs="+quotes"]
----
...
rosa-fruits-app-quarkus-547d97fd7-mp274 #devkameshs-rosa-fruits-app-quarkus java.util.NoSuchElementException: No value present#<.>
rosa-fruits-app-quarkus-547d97fd7-mp274 devkameshs-rosa-fruits-app-quarkus      at java.base/java.util.Optional.orElseThrow(Optional.java:382)
rosa-fruits-app-quarkus-547d97fd7-mp274 devkameshs-rosa-fruits-app-quarkus      at dev.kameshs.rosa.RdsIamAuthenticationProvider.getCredentials(RdsIamAuthenticationProvider.java:72)
rosa-fruits-app-quarkus-547d97fd7-mp274 devkameshs-rosa-fruits-app-quarkus      at dev.kameshs.rosa.RdsIamAuthenticationProvider_ClientProxy.getCredentials(RdsIamAuthenticationProvider_ClientProxy.zig:128)
...
----

As the OpenShift SA from *demos* namespace does not have authorization, the Pod Identity Webhook has not injected the `AWS_ROLE_ARN` environment variable inside the pod, resulting in the error.